app/blueprints/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__, template_folder='templates', static_folder='static')

from app.blueprints.users import routes

app/blueprints/users/routes.py
from flask import render_template, redirect, url_for, flash
from app.models import User
from flask_login import login_required, current_user
from app.blueprints.users import users

@users.route('/')
def index():
  context = {
    'users': [i for i in User.query.all() if i.id != current_user.id],
  }
  return render_template('users/index.html', **context)

@users.route('/add/<user>')
@login_required
def add(user):
  user = User.query.filter_by(name=user).first()
  if user not in current_user.followed:
    current_user.follow(user)
    flash("User added successfully", "success")
    return redirect(url_for('users.index'))
  flash(f"You are already following {user.name}", "warning")
  return redirect(url_for('users.index'))

@users.route('/remove/<user>')
@login_required
def remove(user):
  user = User.query.filter_by(name=user).first()
  if user in current_user.followed:
    current_user.unfollow(user)
    flash("User removed successfully", "info")
    return redirect(url_for('users.index'))
  flash("You cannot unfollow someone you're not following. Make it make sense, sis...", "danger")
  return redirect(url_for('users.index'))

@users.route('/delete/<user>')
@login_required
def delete(user):
  user = current_user
  db.session.delete(user)
  db.session.commit()
  flash("Your account was deleted successfully. Sorry to see you go.", "info")
  return redirect(url_for('users.index'))

app/blueprints/users/templates/users/index.html
{% extends 'layout.html' %}

{% block title %} {{ super() }} - Users {% endblock %}

{% set active_page="users.index" %}

{% block content %}
<h4>This is the users page</h4>
<hr>

<div class="col-md-6 offset-md-3">
  <table class="table table-striped table-inverse">
      <tbody>
        {% if users %}
          {% for u in users %}
            <tr>
              <td>
                {{ u }}
                {% if current_user.is_following(u) %}
                  <span class="float-right"><a href="{{ url_for('users.remove', user=u) }}" class="btn btn-warning"> Unfollow - </a></span>
                {% else %}
                  <span class="float-right"><a href="{{ url_for('users.add', user=u) }}" class="btn btn-success"> Follow + </a></span>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        {% endif %}
      </tbody>
  </table>
</div>
{% endblock %}