app/blueprints/apis/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

class ErgastForm(FlaskForm):
  year = StringField(validators=[DataRequired()])
  season = StringField(validators=[DataRequired()])
  submit = SubmitField('Submit')

class WeatherForm(FlaskForm):
  city = StringField(validators=[DataRequired()])
  country = StringField(validators=[DataRequired()])
  units = SelectField(coerce=int, choices=[(0, 'Imperial'), (1, 'Metric'), (2, 'Kelvin')], default=0)
  submit = SubmitField('Submit')

app/blueprints/apis/__init__.py
from flask import Blueprint

apis = Blueprint('apis', __name__, template_folder='templates', static_folder='static')

from app.blueprints.apis import routes

app/blueprints/apis/routes.py
from flask import render_template, redirect, url_for
from app.blueprints.apis import apis
import requests
from app.blueprints.apis.forms import ErgastForm, WeatherForm
from flask_login import login_required
import os, math

@apis.route('/ergast', methods=['GET', 'POST'])
@login_required
def ergast():
  form = ErgastForm()
  response = None
  data = None
  if form.validate_on_submit():
    try:
      response = requests.get(f'https://ergast.com/api/f1/{form.year.data}/{form.season.data}/driverStandings.json')
      data = response.json()['MRData']['StandingsTable']['StandingsLists'][0]['DriverStandings']
      context = {
        'data': data,
        'form': form
      }
      return render_template('apis/ergast.html', **context)
    except IndexError:
      context = {
        'data': data,
        'form': form,
        'message': 'There are no results for that year or season'
      }
      return render_template('apis/ergast.html', **context)
    except:
      context = {
        'data': data,
        'form': form,
        'message': 'That is an invalid entry'
      }
      return render_template('apis/ergast.html', **context)
  context = {
    'form': form,
    'data': data,
    'message': 'Search for something...'
  }
  return render_template('apis/ergast.html', **context)

@apis.route('/weather', methods=['GET', 'POST'])
@login_required
def weather():
  form = WeatherForm()
  response = None
  data = None
  unit = None
  if form.validate_on_submit():
    if form.units.data == 0:
      unit = "°F"
    elif form.units.data == 1:
      unit = "°C"
    else:
      unit = "K"
    try:
      response = requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={form.city.data},{form.country.data}&appid={os.environ.get("OPENWEATHERMAP_API_KEY")}&units={dict(form.units.choices).get(form.units.data)}')
      data = response.json()
      context = {
        'data': dict(
          name=data['name'],
          country=data['sys']['country'],
          current=math.floor(data['main']['temp']),
          condition=data['weather'][0]['main'],
          clouds=data['clouds']['all'],
          high_temp=math.floor(data['main']['temp_max']),
          low_temp=math.floor(data['main']['temp_min']),
          unit=unit
        ),
        'form': form,
      }
      return render_template('apis/openweathermap.html', **context)
    except IndexError:
      context = {
        'data': data,
        'form': form,
        'message': 'There are no results for that year or season'
      }
      return render_template('apis/openweathermap.html', **context)
    except Exception as e:
      context = {
        'data': data,
        'form': form,
        'message': 'That is an invalid entry'
      }
      print('Error', e)
      return render_template('apis/openweathermap.html', **context)
  context = {
    'form': form,
    'data': data,
    'message': 'Search for something...'
  }
  return render_template('apis/openweathermap.html', **context)

app/blueprints/apis/templates/apis/ergast.html
{% extends 'layout.html' %}

{% block title %} {{ super() }} - Ergast API {% endblock %}

{% set active_page="apis.ergast" %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('apis.static', filename='css/apis.css') }}">
{% endblock %}

{% block content %}
<div class="col-md-4 form-container">
  <form class="form-inline ergast-form" action="{{ url_for('apis.ergast') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.year(class="form-control", placeholder="Year") }}
      {{ form.season(class="form-control", placeholder="Season") }}
      {{ form.submit(class="btn btn-info") }}
    </div>
  </form>
</div>
<hr />
<div class="col-md-12">
  {% if message or not data %}
    <p>{{ message }}</p>
  {% else %}
    <table class="table table-striped table-inverse">
      <thead class="thead-inverse">
        <tr>
          <th>Position</th>
          <th>Name</th>
          <th>Nationality</th>
          <th>Constructor</th>
          <th>Points</th>
          <th>Wins</th>
        </tr>
      </thead>
      <tbody>
        {% for i in data %}
        <tr>
          <td>{{ i.position }}</td>
          <td><a href="{{ i.Driver.url }}">{{ "{} {}".format(i.Driver.givenName, i.Driver.familyName) }}</a></td>
          <td>{{ i.Driver.nationality }}</td>
          <td><a href="{{ i.Constructors[0].url }}">{{ i.Constructors[0].name }}</a></td>
          <td>{{ i.points }}</td>
          <td>{{ i.wins }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
</div>

{% endblock %}

app/blueprints/apis/templates/apis/openweathermap.html
{% extends 'layout.html' %}

{% block title %} {{ super() }} - OpenWeatherMap API {% endblock %}

{% set active_page="apis.ergast" %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('apis.static', filename='css/apis.css') }}">
{% endblock %}

{% block content %}
<div class="col-md-4 form-container">
  <form class="form-inline ergast-form" action="{{ url_for('apis.weather') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.city(class="form-control", placeholder="City") }}
      {{ form.country(class="form-control", placeholder="Country") }}
      {{ form.units(class="form-control") }}
      {{ form.submit(class="btn btn-info") }}
    </div>
  </form>
</div>
<hr />
<div class="col-md-6">
  {% if message or not data %}
    <p>{{ message }}</p>
  {% else %}
    <p>
      <div>
        <h3>
          <span class="badge badge-default">City</span>
          <span class="float-right badge badge-default">{{ data.name }}</span>
        </h3>
      </div>
    </p>
    <p>
      <div>
        <h3>
          <span class="badge badge-default">Country</span>
          <span class="float-right badge badge-default">{{ data.country }}</span>
        </h3>
      </div>
    </p>
    <p>
      <div>
        <h3>
          <span class="badge badge-info">Current Temp</span>
          <span class="float-right badge badge-default">{{ data.current }}{{ data.unit }}</span>
        </h3>
      </div>
    </p>
    <p>
      <div>
        <h3>
          <span class="badge badge-light">Condition</span>
          <span class="float-right badge badge-default">{{ data.condition }}</span>
        </h3>
      </div>
    </p>
    <p>
      <div>
        <h3>
          <span class="badge badge-dark">Clouds</span>
          <span class="float-right badge badge-default">{{ data.clouds }}&percnt;</span>
        </h3>
      </div>
    </p>
    <p>
      <div>
        <h3>
          <span class="badge badge-warning">High Temp</span>
          <span class="float-right badge badge-default">{{ data.high_temp }}{{ data.unit }}</span>
        </h3>
      </div>
    </p>
    <p>
      <div>
        <h3>
          <span class="badge badge-primary">Low Temp</span>
          <span class="float-right badge badge-default">{{ data.low_temp }}{{ data.unit }}</span>
        </h3>
      </div>
    </p>
  {% endif %}
</div>

{% endblock %}