app/blueprints/projects/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField
from wtforms.validators import DataRequired

class AutomationForm(FlaskForm):
  database = SelectField(validators=[DataRequired()], choices=[(0, '-- Select a Database --')], coerce=int)
  table = SelectField(validators=[DataRequired()], choices=[(0, '-- Select a Table --')], coerce=int)
  submit = SubmitField()

class ProductForm(FlaskForm):
  quantity = SelectField(validators=[DataRequired()], choices=[(0, '-- Select a quantity --')], coerce=int)
  submit = SubmitField('Add to cart')

app/blueprints/projects/__init__.py
from flask import Blueprint

projects = Blueprint('projects', __name__, template_folder='templates', static_folder='static')

from app.blueprints.projects import routes

app/blueprints/projects/routes.py
from flask import render_template, redirect, url_for, flash, session
from app.blueprints.projects import projects
from flask_login import login_required
from app.blueprints.projects.forms import AutomationForm, ProductForm
from app.blueprints.projects.connection import connection, populate_form_from_database
import math, statistics, mysql.connector, os, stripe
from app.blueprints.projects.stripe import initProducts, convert_price

@projects.route('/automation', methods=['GET', 'POST'])
@login_required
def automation():
  form = AutomationForm()
  session['database'] = form.database.data
  form.database.data = session['database']
  if form.database.data is None:
    # print("form.database.data is:", "Unefined")
    conn = connection()
    populate_form_from_database(conn, 'databases', form.database)
    session['databases_choices'] = form.database.choices
    context = {
      'form': form,
      'label': 'Search Database',
    }
    return render_template('projects/automation.html', **context)
  else:
    # print("form.database.data is:", "Defined")
    form.database.data = session['database'] # set database choice to last selected database from previous redirect
    conn = connection(session['databases_choices'][form.database.data][1].lower())
    populate_form_from_database(conn, 'databases', form.database)
    populate_form_from_database(conn, 'tables', form.table)
    if form.validate_on_submit():
      if not form.table.choices:
        flash("Must select a valid option. Try again", "warning")
      cur = conn.cursor()
      cur.execute(f"SELECT * FROM {form.table.choices[form.table.data][1].lower()}")
      data = cur.fetchall()
      context = {
        'form': form,
        'data': dict(
                  rows=data,
                  columns=cur.column_names,
                ),
        'is_database': True,
        'is_table': True,
        'label': 'Search Table'
      }
      cur.close()
      conn.close()
      flash("Successful database query", "success")
      return render_template('projects/automation.html', **context)
    context = {
      'form': form,
      'is_database': True,
      'label': 'Search Table',
    }
    return render_template('projects/automation.html', **context)

@projects.route('/ecommerce')
@login_required
def ecommerce():
  productForm = ProductForm()
  productForm.quantity.choices.extend([(i, i) for i in range(1, 100)])
  try:
    if not session['cart']:
      initProducts()
      pass
  except:
    session['cart'] = list()
  if productForm.validate_on_submit():
    print('It works')
    flash("Item added to the cart")
    return redirect(url_for('projects.ecommerce'))
  context = {
    'products': initProducts(),
    'productForm': productForm
  }
  return render_template('projects/ecommerce.html', **context)

@projects.route('/ecommerce/cart')
@login_required
def ecommerceCart():
  try:
    shallowCart = []
    for i in session['cart']:
      if i not in shallowCart:
        shallowCart.append(i)
    for i in shallowCart:
      i['quantity'] = session['cart'].count(i)
  except:
    session['cart'] = list()
    initProducts()
  context = {
    'products': initProducts(),
    'cart': session['cart'],
    'shallowCart': shallowCart,
    'grandTotal': round(sum([i['price'] for i in session['cart']]), 2),
    'round': round
  }
  return render_template('projects/ecommerce-cart.html', **context)

@projects.route('/ecommerce/cart/add/product/<id>', methods=['GET', 'POST'])
@login_required
def ecommerceCartAdd(id):
  p = stripe.SKU.retrieve(id)
  product = dict(
    id=p.id,
    prod_id=p.product,
    name=p.attributes.name,
    image=p.image,
    price=convert_price(p.price)
  )
  session['cart'].append(product)
  flash(f"[{product['name']}] added to your shopping cart.", "info")
  return redirect(url_for('projects.ecommerce'))

@projects.route('/ecommerce/cart/clear')
@login_required
def ecommerceCartClear():
  if session['cart']:
    session['cart'] = list()
    flash("You have cleared all items from your cart.", "info")
  else:
    flash("You cannot clear items from a cart you don't have.", "warning")
  return redirect(url_for('projects.ecommerceCart'))

@projects.route('/ecommerce/cart/remove/<id>')
@login_required
def ecommerceCartRemove(id):
  product = stripe.SKU.retrieve(id)
  try:
    for i in session['cart']:
      if product['id'] == i['id']:
        session['cart'].remove(i)
        flash(f"You have removed {product.attributes.name}.", "info")
        break
  except:
    flash(f"{product.attributes.name} could not be removed", "warning")
  return redirect(url_for('projects.ecommerceCart'))

@projects.route('/ecommerce/cart/product/add/<product>', methods=['POST'])
@login_required
def ecommerceCartProductAdd(product):
  form = ProductForm()
  if form.submit():
    for i in initProducts():
      if product == i['name']:
        session['cart'].extend([i] * form.quantity.data)
        break
    flash(f"You've added {form.quantity.data} {product}(s) to your cart.", "info")
  return redirect(url_for('projects.ecommerce'))

@projects.route('/databases')
@login_required
def databases():
  context = {
  }
  return render_template('projects/databases.html', **context)

app/blueprints/projects/templates/projects/automation.html
{% extends 'layout.html' %}

{% block title %} {{ super() }} - Automation {% endblock %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('projects.static', filename='css/projects.css') }}">
{% endblock %}

{% set active_page="projects.automation" %}

{% block content %}
  <h4>This is the automation page</h4>

  <hr>
  
  <div class="col-md-4 content-container">
    <form class="form-inline form-automation" action="{{ url_for('projects.automation') }}" method="POST">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.database(class="form-control") }}
        {% if is_database %}{{ form.table(class="form-control") }}{% endif %}
        {{ form.submit(label=label, value=label, class="btn btn-primary") }}
      </div>
    </form>

    {% if is_table %}
      <a href="{{ url_for('projects.automation') }}" class="btn btn-danger reset-search">Reset Search</a>
    {% endif %}
  </div>
  
  {% if not data %}
    <table class="table table-inverse table-responsive">
      <thead class="thead-inverse">
        <tr>
          <th>Search for data...</th>
        </tr>
        </thead>
    </table>
  {% else %}
    <table class="table table-striped table-inverse table-responsive">
      <thead class="thead-inverse">
        <tr>
          {% for i in data.columns %}
            <th>{{ i }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for i in data.rows %}
          <tr>
            {% for tup in i %}
              <td>{{ tup }}</td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}

{% endblock %}

{% block scripts %}
    {{ super() }}
    {% if is_table %}
      <script>
        var dropdownList = $('select')[0].options
        for (let i = 0; i < dropdownList.length; i++) {
          if (!dropdownList[i].selected) {
            dropdownList[i].disabled = true
          }
        }
      </script>
    {% endif %}
{% endblock %}

app/blueprints/projects/templates/projects/databases.html
{% extends 'layout.html' %}

{% block title %} {{ super() }} - Databases {% endblock %}

{% set active_page="projects.databases" %}

{% block content %}
  <h4>This is the databases page</h4>
  <hr>

{% endblock %}

app/blueprints/projects/templates/projects/ecommerce-cart.html
{% extends 'layout.html' %}

{% block title %} {{ super() }} - E-commerce Cart {% endblock %}

{% block scripts %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('projects.static', filename='css/projects.css') }}">
{% endblock %}

{% set active_page="projects.ecommerceCart" %}

{% block content %}
  <h4>
    This is the e-commerce cart page
    <span class="float-right"><a {% if cart %}href="{{ url_for('projects.ecommerceCartClear') }}"{% endif %} class="btn btn-danger">Clear cart</a></span>
  </h4>
  
  {% if not cart %}
    <p>You have no items in the cart.</p>
    <hr>
  {% else %}
    <table id="cart" class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Description</th>
          <th>Price</th>
          <th>Quantity</th>
          <th class="text-center">Subtotal</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for p in shallowCart %}
          <tr>
            <td data-th="Product">
              <div class="row">
                <div class="col-sm-2 hidden-xs"><img src="{{ p.image }}" alt="{{ p.name }}" class="img-fluid" /></div>
                <div class="col-sm-10">
                  <h4 class="nomargin">{{ p.name }}</h4>
                  <p>Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet.</p>
                </div>
              </div>
            </td>
            <td data-th="Price">${{ p.price }}</td>
            <td data-th="Quantity">x{{ p.quantity }}</td>
            <td data-th="Subtotal" class="text-center">${{ round(p.price * p.quantity, 2) }}</td>
            <td class="actions" data-th="">
              <a href="{{ url_for('projects.ecommerceCartRemove', id=p.id) }}" class="btn btn-danger btn-sm">Remove</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td><a href="{{ url_for('projects.ecommerce') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
          <td colspan="2" class="hidden-xs"></td>
          <td class="hidden-xs text-center"><strong>${{ grandTotal }}</strong></td>
          <td><a href="#" class="btn btn-success btn-block">Pay <i class="fa fa-angle-right"></i></a></td>
        </tr>
      </tfoot>
    </table>
  {% endif %}

{% endblock %}

app/blueprints/projects/templates/projects/ecommerce.html
{% extends 'layout.html' %}

{% block title %} {{ super() }} - E-commerce {% endblock %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('projects.static', filename='css/projects.css') }}">
{% endblock %}

{% set active_page="projects.ecommerce" %}

{% block content %}
  <div class="clearfix">
    <h4>
      This is the ecommerce page
      <span class="float-right"><a href="{{ url_for('projects.ecommerceCart') }}" class="btn btn-primary">Show cart</a></span>
    </h4>
    
    <hr>
  </div>
  <div class="row">
    {% for p in products %}
      <div class="col-md-4">
        <figure class="card card-product">

          <!-- Button trigger modal -->
          <button type="button" class="btn btn-link" data-toggle="modal" data-target="#productModal_{{ p.id }}"><i class="fa fa-search-plus"></i> Quick view</button>
          <!-- Modal -->
          {% include 'projects/partials/ecommerce-product.html' %}

          <div class="img-wrap">
            <img class="img-fluid" src="{{ p.image }}" />
            <!-- <a class="btn-overlay" href="#"><i class="fa fa-search-plus"></i> Quick view</a> -->
          </div>
          <figcaption class="info-wrap">
            <h6 class="title text-dots"><a href="#" data-toggle="modal" data-target="#productModal_{{ p.id }}">{{ p.name }}</a></h6>
            <div class="action-wrap">
              <a href="{{ url_for('projects.ecommerceCartAdd', id=p.id) }}" class="btn btn-primary btn-sm float-right"> Add to cart </a>
              <div class="price-wrap h5">
                <span class="price-new">${{ p.price }}</span>
                <!-- <del class="price-old">$1980</del> -->
              </div> <!-- price-wrap.// -->
            </div> <!-- action-wrap -->
          </figcaption>
        </figure> <!-- card // -->
      </div> <!-- col // -->
    {% endfor %}
  </div> <!-- row.// -->
  
{% endblock %}

app/blueprints/projects/templates/projects/partials/ecommerce-product.html
<div class="modal fade" id="productModal_{{ p.id }}">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="{{ p.image }}" alt="{{ p.name }}" class="img-fluid">
        <p>
          <h4>
            {{ p.name }}
            <span class="float-right">${{ p.price }}</span>
          </h4>
        </p>
        <p>Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet.</p>
        <form class="form-inline product-form" action="{{ url_for('projects.ecommerceCartProductAdd', product=p.name ) }}" method="POST">
          {{ productForm.hidden_tag() }}
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6" style="padding: 0 5px 0 0;">
                {{ productForm.quantity(style="min-width: 100%; text-align-last:center; text-align:center;", class="form-control") }}
              </div>
              <div class="col-md-6" style="padding: 0 0 0 5px;">
                {{ productForm.submit(style="min-width: 100%;", type="submit", class="form-control btn btn-primary float-right") }}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>